name: educompany_mobile
description: "A premium educational mobile platform"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  go_router: ^14.8.1
  rive: ^0.14.3
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  percent_indicator: ^4.2.3
  fl_chart: ^0.70.2
  table_calendar: ^3.2.0
  cached_network_image: ^3.4.1
  video_player: ^2.11.0
  supabase_flutter: ^2.12.0
  file_picker: ^8.0.0+1
  http: ^1.2.1
  image_picker: ^1.0.7
  path: ^1.9.0
  mime: ^1.0.5
  flutter_markdown: ^0.7.4
  syncfusion_flutter_pdf: ^32.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/videos/
